version: '3.7'
services:
    app:
      image: demo/laravel
      restart: always
      environment:
        TZ: Asia/Ho_Chi_Minh
      ports:
        - 80:80
        - 9117:9117
      volumes:
        - ./:/var/www/html
        - ./log:/var/log/apache2/
        - ./log/exporter:/var/log/supervisor/