version: '3.7'
services:
    #PHP Service
    app:
      image: demo/laravel:v2
      restart: always
      ports:
        - 80:80
        - 9117:9117
      volumes:
        - ./:/var/www/html
        #- ./apache/apache2.conf:/etc/apache2/apache2.conf
        - ./apache_exporter.service:/etc/systemd/system/apache_exporter.service
