version: '3.7'
services:
    app:
      image: demo/laravel
      restart: always
      ports:
        - 80:80
        - 9117:9117
      volumes:
        - ./:/var/www/html
        - ./mods-available/status.conf:/etc/apache2/mods-available/status.conf