FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl wget vim git zip unzip zlib1g-dev libzip-dev libpng-dev
RUN apt-get install -y software-properties-common \
        && add-apt-repository ppa:ondrej/php \
        && apt-get update \
        && apt-get install -y php7.4 php7.4-cli php7.4-json php7.4-common php7.4-mysql php7.4-zip php7.4-gd php7.4-mbstring php7.4-curl php7.4-xml php7.4-bcmath php7.4-ldap
RUN apt-get install -y nodejs \
        && apt-get install -y npm \
        && apt-get install -y apache2

ADD site.conf /etc/apache2/sites-available/
RUN a2enmod headers && a2enmod rewrite && a2dissite 000-default && a2ensite site
WORKDIR /
RUN curl -s https://api.github.com/repos/Lusitaniae/apache_exporter/releases/latest   | grep browser_download_url   | grep linux-amd64 | cut -d '"' -f 4 | wget -qi -
RUN tar xvf apache_exporter-*.linux-amd64.tar.gz
# Configure directory permissions for the web server
EXPOSE 80 9117
ENTRYPOINT ["/var/www/html/entrypoint.sh"]
