version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:latest
  command: server --console-address ":9001" http://minio/data
  expose:
    - 8081:9000
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: L9UU75judxgjBPXk
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio1:
    <<: *minio-common
    volumes:
      - ./image.his/data:/data
    networks:
      - deploy_default

networks:
  deploy_default:
    external: true