version: '3.7'
services:
    apache:
#      build:
#        context: .
#        dockerfile: Dockerfile
      image: apache:v1
      restart: always
      ports:
        - 80:80
        - 9000:9000
      volumes:
        - ./:/var/www/html
    exporter:
#      build:
#        context: .
#        dockerfile: DockerfileExporter
      image: exporter:v1
      restart: always
      ports:
        - 9117:9117
      command: /usr/local/bin/apache_exporter --insecure --scrape_uri=http://tinnc.com.vn/server-status/?auto --telemetry.address=0.0.0.0:9117 --telemetry.endpoint=/metrics