version: '3.7'
services:
    app:
      image: demo/apache
      restart: always
      ports:
        - 80:80
        - 9000:9000
      volumes:
        - ./:/var/www/html
#    app:
#      image: demo/exporter
#      restart: always
#      ports:
#        - 9117:9117